using Kentico.Forms.Web.Mvc;

[assembly: RegisterFormSection("Bootstrap.TwoColumn", "Two columns 50-50","~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapTwoColumnFormSection.cshtml", Description = "Organizes fields into two equal-width columns.", IconClass = "icon-l-cols-2")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn2575", "Two columns 25-75", "~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapTwoColumn2575FormSection.cshtml", Description = "Organizes fields into two columns, 25% and 75% widget.", IconClass = "icon-l-cols-20-80")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn7525", "Two columns 75-25", "~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapTwoColumn7525FormSection.cshtml", Description = "Organizes fields into two columns, 75% and 25% widget.", IconClass = "icon-l-cols-80-20")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn3366", "Two columns 33-66", "~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapTwoColumn3366FormSection.cshtml", Description = "Organizes fields into two columns, 33% and 66% widget.", IconClass = "icon-l-cols-30-70")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn6633", "Two columns 66-33", "~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapTwoColumn6633FormSection.cshtml", Description = "Organizes fields into two columns, 66% and 33% widget.", IconClass = "icon-l-cols-70-30")]
[assembly: RegisterFormSection("Bootstrap.ThreeColumn", "Three Columns", "~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapThreeColumnFormSection.cshtml", Description = "Organizes fields into three equal-width columns.", IconClass = "icon-l-cols-3")]
[assembly: RegisterFormSection("Bootstrap.FourColumn", "Four Columns", "~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapFourColumnFormSection.cshtml", Description = "Organizes fields into four equal-width columns.", IconClass = "icon-l-cols-4")]
[assembly: RegisterFormSection("Bootstrap.FiveColumn", "Five Columns", "~/Views/Components/FormSections/BootstrapLayoutTool/_BootstrapFiveColumnFormSection.cshtml", Description = "Organizes fields into five equal-width columns.", IconClass = "icon-l-cols-4")]
[assembly: RegisterFormSection("Bootstrap.SixColumn", "Six Columns", "~/Views/Components/FormSections/BootstrapLayoutTool/FormSections/_BootstrapSixColumnFormSection.cshtml", Description = "Organizes fields into six equal-width columns.", IconClass = "icon-l-cols-4")]