using Kentico.Forms.Web.Mvc;

[assembly: RegisterFormSection("Bootstrap.TwoColumn", "Two columns 50-50","", Description = "Organizes fields into two equal-width columns.", IconClass = "icon-l-cols-2")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn2575", "~/Views/Components/FormSections/_BootstrapTwoColumn2575FormSection.cshtml", "Two columns 25-75", Description = "Organizes fields into two columns, 25% and 75% widget.", IconClass = "icon-l-cols-20-80")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn7525", "~/Views/Components/FormSections/_BootstrapTwoColumn7525FormSection.cshtml", "Two columns 75-25", Description = "Organizes fields into two columns, 75% and 25% widget.", IconClass = "icon-l-cols-80-20")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn3366", "~/Views/Components/FormSections/_BootstrapTwoColumn3366FormSection.cshtml", "Two columns 33-66", Description = "Organizes fields into two columns, 33% and 66% widget.", IconClass = "icon-l-cols-30-70")]
[assembly: RegisterFormSection("Bootstrap.TwoColumn6633", "~/Views/Components/FormSections/_BootstrapTwoColumn6633FormSection.cshtml", "Two columns 66-33", Description = "Organizes fields into two columns, 66% and 33% widget.", IconClass = "icon-l-cols-70-30")]
[assembly: RegisterFormSection("Bootstrap.ThreeColumn", "~/Views/Components/FormSections/_BootstrapThreeColumnFormSection.cshtml", "Three Columns", Description = "Organizes fields into three equal-width columns.", IconClass = "icon-l-cols-3")]
[assembly: RegisterFormSection("Bootstrap.FourColumn", "~/Views/Components/FormSections/_BootstrapFourColumnFormSection.cshtml", "Four Columns", Description = "Organizes fields into four equal-width columns.", IconClass = "icon-l-cols-4")]
[assembly: RegisterFormSection("Bootstrap.FiveColumn", "~/Views/Components/FormSections/_BootstrapFiveColumnFormSection.cshtml", "Five Columns", Description = "Organizes fields into five equal-width columns.", IconClass = "icon-l-cols-4")]
[assembly: RegisterFormSection("Bootstrap.SixColumn", "~/Views/Components/FormSections/FormSections/_BootstrapSixColumnFormSection.cshtml", "Six Columns", Description = "Organizes fields into six equal-width columns.", IconClass = "icon-l-cols-4")]